### ISSUE TITLE
Needs PyPI release

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/z3c.recipe.compattest#4]
PR #3 updated supported Python versions and fixed some resource leaks. A PyPI release would be great. Could one of the PyPI maintainers please grant me (`jamadden`) and @mgedmin (`mgedmin`) PyPI rights? [The PyPI maintainers](https://pypi.org/project/z3c.recipe.compattest/) appear to include @janjaapdriessen @jimfulton @hannosch @janwijbrand @ctheune @thefunny42 .

**Comment by jamadden** [comment]
Gentle ping to the maintainers ( @janjaapdriessen @jimfulton @hannosch @janwijbrand @ctheune @thefunny42  ) that it would be nice to get a PyPI release of this recipe.

**Comment by janjaapdriessen** [comment]
My apologies Jason, I missed earlier mention. I have added you and Marius as owners on pypi.

**Comment by jamadden** [comment]
Thank you very much! I've uploaded 1.1.0.
